Upgrade to the latest operator-sdk
open-cluster-management/iam-policy-controller pull request #78
Opened 2021-11-01 14:18 UTC by mprahl

The first commit removed some unused code regarding namespace selectors. This made fixing the tests after the operator-sdk upgrade easier.

operator-sdk v1.x now wraps Kubebuilder for its scaffolding and code
generation. This changes the path of `./cmd/manager/main.go` to
`.main.go`, `./pkg/controller` to `./controllers`, and `pkg/apis` to
`api`.

Manifest generation is also handled by Kubebuilder. This is handled by
the `generate-operator-yaml` Make target. This means that any RBAC
changes must be done using kubebuilder markers and not manual edits to
the manifests in `./deploy`. The RBAC Kubebuilder markers have been
refined to follow the least privilege principal.

The largest changes stem from updating the underlying Kubernetes Go
modules as some APIs changed or were removed. This also leads to a new
way of performing leader election via leases. For old Kubernetes
versions such as OCP 3.11, the lease API is not available so a flag
called `--legacy-leader-election` will go back to the old way of
performing leader election.

It's also important to note that operator-sdk is no longer a Go module
dependency, so some functionality was copied over, mostly unmodified.

Lastly, the Policy scheme is now imported from the propagator rather
than redefined in this controller.

Relates:
open-cluster-management/backlog#15552

2021-11-01 14:24 UTC, mprahl commented
The Dockerfile looks like a new file but it's just because I removed the symlink from Dockerfile to build/Dockerfile. This was a previous workaround for operator-sdk v0.19.4.

2021-11-01 17:02 UTC, JustinKuli requested changes
Looks good overall! Just one question and a small requested change

2021-11-01 17:36 UTC, mprahl commented
@ckandag could I please get your input on the ACL refactoring? It works as expected based on my testing and running the framework tests on it but I'd like your opinion as well.

2021-11-01 17:36 UTC, JustinKuli commented on Makefile
> +	@docker build -t ${IMAGE_NAME_AND_VERSION} .
Ok, now I see the prow config here: https://github.com/openshift/release/blob/master/ci-operator/config/open-cluster-management/iam-policy-controller/open-cluster-management-iam-policy-controller-release-2.4.yaml#L13, and that's pointing to `./Dockerfile`.

AFAIK, the other controllers still use `./build/Dockerfile`, for example: https://github.com/openshift/release/blob/master/ci-operator/config/open-cluster-management/config-policy-controller/open-cluster-management-config-policy-controller-release-2.4.yaml#L13

I guess it doesn't matter.

2021-11-01 17:37 UTC, JustinKuli commented
/approve
/hold for another review

2021-11-01 17:37 UTC, JustinKuli approved these changes

2021-11-02 15:22 UTC, gparvin approved these changes
I'm not sure I understand how it needs only `clusterrolebindings` and not also `clusterroles`, but definitely glad to see least privilege is being improved.  Thanks for putting in the effort to improve that.

2021-11-02 16:59 UTC, mprahl commented
> I'm not sure I understand how it needs only `clusterrolebindings` and not also `clusterroles`, but definitely glad to see least privilege is being improved. Thanks for putting in the effort to improve that.

I think we could tighten this up with a role (not cluster role) for how it accesses the hub config secret it needs for creating the lease since that should always be in the `open-cluster-management-agent-addon` namespace.

Since the Helm chart in the klusterlet-addon-operator just uses a cluster role, I'll keep it as is in this PR and file a separate issue for that.

2021-11-02 17:01 UTC, merged